-- ============================================================
-- BASE DE DATOS SUPABASE (POSTGRESQL)
-- BIBLIOTECA COLEGIO HUMBOLDT
-- ============================================================
-- Instrucciones:
-- 1. Ve a tu panel de Supabase: https://supabase.com/dashboard
-- 2. Entra en tu proyecto y ve a la sección "SQL Editor" (menú lateral izquierdo).
-- 3. Haz clic en "New query", pega todo este contenido y presiona "Run".
-- ============================================================

-- 1. Crear tabla de libros
CREATE TABLE IF NOT EXISTS public.libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    autor TEXT NOT NULL,
    categoria TEXT NOT NULL,
    editorial TEXT,
    anio INTEGER,
    isbn TEXT,
    estado TEXT DEFAULT 'Disponible',
    copias_total INTEGER DEFAULT 1,
    copias_disponibles INTEGER DEFAULT 1,
    imagen TEXT,
    ubicacion JSONB DEFAULT '{"estanteria": "Estantería A", "seccion": "General", "nivel": "Nivel 1"}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Crear índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_libros_titulo ON public.libros (titulo);
CREATE INDEX IF NOT EXISTS idx_libros_autor ON public.libros (autor);
CREATE INDEX IF NOT EXISTS idx_libros_categoria ON public.libros (categoria);
CREATE INDEX IF NOT EXISTS idx_libros_estado ON public.libros (estado);

-- 3. Configurar Políticas de Seguridad (Row Level Security - RLS)
ALTER TABLE public.libros ENABLE ROW LEVEL SECURITY;

-- REGLA 1: Permitir lectura pública a todos (estudiantes, docentes, anónimos y autenticados)
DROP POLICY IF EXISTS "Permitir lectura publica de libros" ON public.libros;
DROP POLICY IF EXISTS "Permitir solo lectura a publico anonimo" ON public.libros;
CREATE POLICY "Permitir lectura publica de libros" 
ON public.libros 
FOR SELECT 
TO anon, authenticated
USING (true);

-- REGLA 2: Solo usuarios AUTENTICADOS (Administradores con sesión real) pueden insertar libros
DROP POLICY IF EXISTS "Permitir insertar libros" ON public.libros;
DROP POLICY IF EXISTS "Solo administradores autenticados pueden insertar" ON public.libros;
CREATE POLICY "Solo administradores autenticados pueden insertar" 
ON public.libros 
FOR INSERT 
TO authenticated
WITH CHECK (true);

-- REGLA 3: Solo usuarios AUTENTICADOS pueden modificar libros (editar o prestar/devolver copias)
DROP POLICY IF EXISTS "Permitir actualizar libros" ON public.libros;
DROP POLICY IF EXISTS "Solo administradores autenticados pueden actualizar" ON public.libros;
CREATE POLICY "Solo administradores autenticados pueden actualizar" 
ON public.libros 
FOR UPDATE 
TO authenticated
USING (true);

-- REGLA 4: Solo usuarios AUTENTICADOS pueden eliminar libros
DROP POLICY IF EXISTS "Permitir eliminar libros" ON public.libros;
DROP POLICY IF EXISTS "Solo administradores autenticados pueden eliminar" ON public.libros;
CREATE POLICY "Solo administradores autenticados pueden eliminar" 
ON public.libros 
FOR DELETE 
TO authenticated
USING (true);

-- 4. Opcional: Insertar los 18 libros iniciales de la biblioteca
INSERT INTO public.libros (id, titulo, autor, categoria, editorial, anio, isbn, estado, copias_total, copias_disponibles, imagen, ubicacion)
OVERRIDING SYSTEM VALUE
VALUES
(1, 'El Principito', 'Antoine de Saint-Exupéry', 'Literatura', 'Salamandra', 1943, '978-0156012195', 'Disponible', 4, 3, 'images/cover-1.jpg', '{"estanteria": "Estantería A", "seccion": "Juvenil", "nivel": "Nivel 2"}'::jsonb),
(2, 'Cien años de soledad', 'Gabriel García Márquez', 'Literatura', 'Sudamericana', 1967, '978-0307474728', 'Prestado', 3, 0, 'images/cover-2.jpg', '{"estanteria": "Estantería A", "seccion": "Clásicos Latinoamericanos", "nivel": "Nivel 3"}'::jsonb),
(3, 'Sapiens: De animales a dioses', 'Yuval Noah Harari', 'Historia', 'Debate', 2011, '978-9584255181', 'Disponible', 3, 2, 'images/cover-3.jpg', '{"estanteria": "Estantería C", "seccion": "Historia Universal", "nivel": "Nivel 1"}'::jsonb),
(4, 'El universo en una cáscara de nuez', 'Stephen Hawking', 'Ciencias', 'Crítica', 2001, '978-8484327653', 'Disponible', 2, 1, 'images/cover-4.jpg', '{"estanteria": "Estantería B", "seccion": "Física y Astronomía", "nivel": "Nivel 1"}'::jsonb),
(5, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Literatura', 'Alfaguara', 1605, '978-8420412146', 'Prestado', 2, 0, 'images/cover-5.jpg', '{"estanteria": "Estantería A", "seccion": "Clásicos", "nivel": "Nivel 2"}'::jsonb),
(6, 'Brevísima historia del tiempo', 'Stephen Hawking', 'Ciencias', 'Crítica', 2005, '978-8484326113', 'Disponible', 3, 2, 'images/cover-6.jpg', '{"estanteria": "Estantería B", "seccion": "Física y Astronomía", "nivel": "Nivel 2"}'::jsonb),
(7, 'Cálculo: Una variable', 'James Stewart', 'Matemáticas', 'Cengage Learning', 2015, '978-6075193274', 'Disponible', 5, 4, 'images/cover-7.jpg', '{"estanteria": "Estantería D", "seccion": "Matemáticas", "nivel": "Nivel 1"}'::jsonb),
(8, 'La república', 'Platón', 'Filosofía', 'Gredos', 2000, '978-8424922597', 'Prestado', 2, 0, 'images/cover-8.jpg', '{"estanteria": "Estantería E", "seccion": "Filosofía Clásica", "nivel": "Nivel 3"}'::jsonb),
(9, 'Historia del arte', 'E.H. Gombrich', 'Arte', 'Phaidon', 1950, '978-0714832470', 'Disponible', 3, 1, 'images/cover-9.jpg', '{"estanteria": "Estantería F", "seccion": "Arte y Cultura", "nivel": "Nivel 2"}'::jsonb),
(10, 'El mundo de Sofía', 'Jostein Gaarder', 'Filosofía', 'Siruela', 1991, '978-8478442089', 'Disponible', 4, 2, 'images/cover-10.jpg', '{"estanteria": "Estantería E", "seccion": "Filosofía Juvenil", "nivel": "Nivel 1"}'::jsonb),
(11, '1984', 'George Orwell', 'Literatura', 'Debolsillo', 1949, '978-8497592011', 'Prestado', 3, 0, 'images/cover-11.jpg', '{"estanteria": "Estantería A", "seccion": "Distopías", "nivel": "Nivel 4"}'::jsonb),
(12, 'Código limpio', 'Robert C. Martin', 'Tecnología', 'Anaya', 2009, '978-8441532106', 'Disponible', 2, 2, 'images/cover-12.jpg', '{"estanteria": "Estantería G", "seccion": "Programación", "nivel": "Nivel 1"}'::jsonb),
(13, 'Física conceptual', 'Paul Hewitt', 'Ciencias', 'Pearson', 2016, '978-6073240222', 'Disponible', 3, 2, 'images/cover-13.jpg', '{"estanteria": "Estantería B", "seccion": "Física General", "nivel": "Nivel 3"}'::jsonb),
(14, 'Álgebra de Baldor', 'Aurelio Baldor', 'Matemáticas', 'Grupo Editorial Patria', 2007, '978-9708170000', 'Disponible', 6, 5, 'images/cover-14.jpg', '{"estanteria": "Estantería D", "seccion": "Álgebra y Aritmética", "nivel": "Nivel 2"}'::jsonb),
(15, 'Rayuela', 'Julio Cortázar', 'Literatura', 'Cátedra', 1963, '978-8437604572', 'Prestado', 2, 0, 'images/cover-15.jpg', '{"estanteria": "Estantería A", "seccion": "Boom Latinoamericano", "nivel": "Nivel 2"}'::jsonb),
(16, 'El arte de la guerra', 'Sun Tzu', 'Historia', 'Edaf', 500, '978-8441432468', 'Disponible', 4, 3, 'images/cover-16.jpg', '{"estanteria": "Estantería C", "seccion": "Historia Antigua", "nivel": "Nivel 2"}'::jsonb),
(17, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Literatura', 'Sudamericana', 1981, '978-0307387738', 'Disponible', 2, 1, 'images/cover-17.jpg', '{"estanteria": "Estantería A", "seccion": "Clásicos Latinoamericanos", "nivel": "Nivel 3"}'::jsonb),
(18, 'Introducción a la programación con Python', 'John Zelle', 'Tecnología', 'Franklin, Beedle & Associates', 2010, '978-1590282755', 'Prestado', 2, 0, 'images/cover-18.jpg', '{"estanteria": "Estantería G", "seccion": "Programación", "nivel": "Nivel 2"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Ajustar la secuencia de IDs al valor máximo actual
SELECT setval(pg_get_serial_sequence('public.libros', 'id'), COALESCE(MAX(id), 1)) FROM public.libros;
